config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'kittens#index'

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all

    respond_to do |format|
       format.html
      format.json { render json: @kittens }
    end

  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
       format.html
      format.json { render json: @kitten }
    end

  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = "Nice you created a kitten"
      redirect_to @kitten
    else
      flash.now[:notice] = "Couldnt create the kitten. Meow"
      render 'new'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:notice] = "You deleted a kitten, sad!"
    redirect_to root_path
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten  = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:notice] = "You updated a kitten, wahoo!"
      redirect_to @kitten
    else
      flash.now[:notice] = "issue"
      render 'edit'
    end
  end


  private #########################################3

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :cuteness %>
  <%= f.number_field :cuteness %>
  <%= f.label :softness %>
  <%= f.number_field :softness %>  
  <%= f.submit "Make the cat!" %>
<% end %>

app/views/kittens/edit.html.erb
<h1> Edit Cat </h1>

<%= render 'form' %>

app/views/kittens/index.html.erb
<h1> All Kittens </h1>
<br>
<br>
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Cuteness</th>
    <th>Softness</th>
    <th>Delete</th>
    <th>Edit</th>
  </tr>

  <% @kittens.each do |kitten| %>
    <tr>
      <th> <%= link_to kitten.name, kitten %> </th>
      <th> <%= kitten.age %> </th>
      <th> <%= kitten.cuteness %>  </th>
      <th> <%= kitten.softness %> </th>
      <th> <%= link_to 'Delete',
                        kitten,
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %> </th>
      <th> <%= link_to "Edit", edit_kitten_path(kitten) %> </th>

    </tr>
  <% end %>



</table>

app/views/kittens/new.html.erb
<h1> New cat </h1>

<%= render 'form' %>

app/views/kittens/show.html.erb
<h1> Show Kitten </h1>
<br>
<br>
<p> Name: <%= @kitten.name %> </p>
<br>
<br>
<p> Age: <%= @kitten.age %> </p>
<br>
<br>
<p> Cuteness: <%= @kitten.cuteness %> </p>
<br>
<br>
<p> Softness: <%= @kitten.softness %> </p>
<br>
<br>

<th> <%= link_to "Edit", edit_kitten_path(@kitten) %> </th>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <br>
    <br>
    <%= link_to "New Kitty", new_kitten_path %>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>